//! Semantic search — embedding-based similarity search using the `search_vector` table.
//!
//! When the `onnx` feature is enabled, embeddings are generated by an ONNX Runtime
//! XLM-R model. Without it, a `StubEmbedder` returns zero vectors (semantic search
//! effectively returns no results, since zero-vectors have zero cosine similarity).
//!
//! The search pipeline:
//! 1. Embed the query text using the configured `TextEmbedder`.
//! 2. Retrieve all stored embedding vectors from the `search_vector` table for the
//!    current model version.
//! 3. Compute cosine similarity between the query embedding and each stored vector.
//! 4. Rank by similarity descending, with recency as a deterministic tiebreaker.

use crate::models::embeddings::TextEmbedder;
use crate::search::SearchError;
use crate::SearchResult;

/// Execute a semantic search against the local embedding index.
///
/// Returns results ranked by cosine similarity to the query embedding.
/// If no embedder is provided, returns an empty vec (semantic search disabled).
pub fn semantic_search(
    db: &crate::local_store::LocalStoreDb,
    query: &str,
    limit: usize,
) -> Result<Vec<SearchResult>, SearchError> {
    semantic_search_with_embedder(db, query, limit, None)
}

/// Execute a semantic search with a custom embedder.
///
/// When `embedder` is `None`, semantic search is disabled and returns empty results.
pub fn semantic_search_with_embedder(
    db: &crate::local_store::LocalStoreDb,
    query: &str,
    limit: usize,
    embedder: Option<&dyn TextEmbedder>,
) -> Result<Vec<SearchResult>, SearchError> {
    let embedder = match embedder {
        Some(e) => e,
        None => return Ok(Vec::new()),
    };

    let query_vec = embedder
        .embed(query)
        .map_err(|e| SearchError::Semantic(e.to_string()))?;

    if query_vec.is_empty() || query_vec.iter().all(|&v| v == 0.0) {
        return Ok(Vec::new());
    }

    let model_version = embedder.model_version();
    let stored = fetch_embeddings(db, model_version)?;

    let mut scored: Vec<(SearchResult, f64, i64)> = stored
        .into_iter()
        .filter_map(|entry| {
            let sim = cosine_similarity(&query_vec, &entry.embedding);
            if sim <= 0.0 {
                return None;
            }

            let message_id = uuid::Uuid::parse_str(&entry.message_id).unwrap_or_default();
            let result = SearchResult {
                message_id,
                conversation_id: uuid::Uuid::nil(),
                sender_id: String::new(),
                created_at_ms: entry.created_at_ms,
                snippet: String::new(),
                score: sim,
                from_cold: false,
            };
            Some((result, sim, entry.created_at_ms))
        })
        .collect();

    // Sort by similarity descending, then by recency for deterministic ordering
    scored.sort_by(|a, b| {
        b.1.partial_cmp(&a.1)
            .unwrap_or(std::cmp::Ordering::Equal)
            .then_with(|| b.2.cmp(&a.2))
    });

    Ok(scored.into_iter().take(limit).map(|(r, _, _)| r).collect())
}

/// Stored embedding entry from the `search_vector` table.
struct StoredEmbedding {
    message_id: String,
    embedding: Vec<f32>,
    created_at_ms: i64,
}

/// Fetch all stored embeddings for a given model version, joined with skeleton
/// metadata for created_at_ms (used as recency tiebreaker).
fn fetch_embeddings(
    db: &crate::local_store::LocalStoreDb,
    model_version: &str,
) -> Result<Vec<StoredEmbedding>, SearchError> {
    let conn = db.read().map_err(|e| SearchError::Custom(e.to_string()))?;

    let mut stmt = conn
        .prepare(
            "SELECT sv.message_id, sv.embedding, ms.created_at_ms
             FROM search_vector sv
             JOIN message_skeleton ms ON sv.message_id = ms.message_id
             WHERE sv.model_version = ?1 AND ms.deleted_at_ms IS NULL",
        )
        .map_err(|e| SearchError::Custom(e.to_string()))?;

    let rows = stmt
        .query_map(rusqlite::params![model_version], |row| {
            let blob: Vec<u8> = row.get(1)?;
            Ok(StoredEmbedding {
                message_id: row.get::<_, String>(0)?,
                embedding: decode_embedding(&blob),
                created_at_ms: row.get::<_, i64>(2)?,
            })
        })
        .map_err(|e| SearchError::Custom(e.to_string()))?;

    let mut result = Vec::new();
    for row in rows {
        result.push(row.map_err(|e| SearchError::Custom(e.to_string()))?);
    }
    Ok(result)
}

/// Decode an INT8-quantized embedding blob back to f32 vectors.
///
/// The encoding is simple: each byte is a signed i8 (-128..127) that maps to
/// the f32 range [-1.0, 1.0] by dividing by 128.0.
fn decode_embedding(blob: &[u8]) -> Vec<f32> {
    blob.iter().map(|&b| (b as i8 as f32) / 128.0).collect()
}

/// Compute cosine similarity between two f32 vectors.
///
/// Returns 0.0 if either vector has zero magnitude (avoiding division by zero).
fn cosine_similarity(a: &[f32], b: &[f32]) -> f64 {
    if a.len() != b.len() || a.is_empty() {
        return 0.0;
    }

    let mut dot = 0.0f64;
    let mut norm_a = 0.0f64;
    let mut norm_b = 0.0f64;

    for (av, bv) in a.iter().zip(b.iter()) {
        dot += (*av as f64) * (*bv as f64);
        norm_a += (*av as f64) * (*av as f64);
        norm_b += (*bv as f64) * (*bv as f64);
    }

    let denom = (norm_a * norm_b).sqrt();
    if denom == 0.0 {
        0.0
    } else {
        dot / denom
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_cosine_similarity_identical() {
        let a = vec![1.0, 0.5, -0.3];
        let sim = cosine_similarity(&a, &a);
        assert!((sim - 1.0).abs() < 1e-6);
    }

    #[test]
    fn test_cosine_similarity_orthogonal() {
        let a = vec![1.0, 0.0];
        let b = vec![0.0, 1.0];
        let sim = cosine_similarity(&a, &b);
        assert!(sim.abs() < 1e-6);
    }

    #[test]
    fn test_cosine_similarity_zero_vector() {
        let a = vec![0.0, 0.0, 0.0];
        let b = vec![1.0, 2.0, 3.0];
        let sim = cosine_similarity(&a, &b);
        assert_eq!(sim, 0.0);
    }

    #[test]
    fn test_cosine_similarity_different_lengths() {
        let a = vec![1.0, 2.0];
        let b = vec![1.0];
        let sim = cosine_similarity(&a, &b);
        assert_eq!(sim, 0.0);
    }

    #[test]
    fn test_decode_embedding() {
        let blob = [0i8 as u8, 64i8 as u8, -64i8 as u8];
        let decoded = decode_embedding(&blob);
        assert!((decoded[0] - 0.0).abs() < 1e-6);
        assert!((decoded[1] - 0.5).abs() < 1e-2);
        assert!((decoded[2] - (-0.5)).abs() < 1e-2);
    }
}
