[package]
name = "cs-core-uniffi"
description = "Swift + Kotlin UniFFI bindings for KChat chat-storage."
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[lib]
crate-type = ["staticlib", "lib", "cdylib"]
name = "cs_core_uniffi"

[dependencies]
cs-core = { path = "../cs-core" }
uniffi = { version = "0.31", features = ["cli"] }
thiserror = { workspace = true }
hex = { workspace = true }
uuid = { workspace = true }
